// Auto-generated by Clark
// Do not edit this file manually

import "@superblocksteam/library";

declare global {
  interface SuperblocksAPIRegistry {
    "GetUserProfile": { input: GetUserProfileInput; output: GetUserProfileResponse };
  }
}
